"""Auto-generated Alembic script
Revision ID: 34b43b602603
Revises: 
Create Date: 2026-07-01 17:24:54.852104
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '34b43b602603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_reviewed_by'), 'applications', ['reviewed_by'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_reviewed_by'), table_name='applications')
    # ### end Alembic commands ###
