"""Auto-generated Alembic script
Revision ID: b6d8806b68f3
Revises: 0001_add_final_review_fields
Create Date: 2026-07-05 18:34:21.368485
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b6d8806b68f3'
down_revision = '0001_add_final_review_fields'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), server_default='Pending', nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=50), server_default='Not Provided', nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=50), server_default='Not Provided', nullable=False))
    op.add_column('users', sa.Column('residential_address', sa.Text(), server_default='Not Provided', nullable=False))
    op.add_column('users', sa.Column('permanent_address', sa.Text(), server_default='Not Provided', nullable=False))
    op.add_column('users', sa.Column('nationality', sa.String(length=100), server_default='Not Provided', nullable=False))
    op.add_column('users', sa.Column('user_status', sa.String(length=50), server_default='Pending', nullable=False))
    op.add_column('users', sa.Column('mobile_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('national_id_number', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pan_tax_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pan_tax_id')
    op.drop_column('users', 'national_id_number')
    op.drop_column('users', 'contact_email')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'user_status')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'permanent_address')
    op.drop_column('users', 'residential_address')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
