"""Auto-generated Alembic script
Revision ID: fce7e0d16671
Revises: b6d8806b68f3
Create Date: 2026-07-06 00:21:09.662348
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fce7e0d16671'
down_revision = 'b6d8806b68f3'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.execute('UPDATE users SET username = email')
    op.alter_column('users', 'username', nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
